### ISSUE TITLE
Will not start.

### ISSUE THREAD

**Issue by NMartin354** [bribribriambriguy/neatonav2#12]
Running slam_launch.py brings up the following error message:

"[ERROR] [launch]: Caught exception in launch (see debug for traceback): not enough values to unpack (expected 2, got 1)"

I set line 16 to

slam = IncludeLaunchDescription(
    PythonLaunchDescriptionSource([        os.path.join(get_package_share_directory('slam_toolbox'), 'launch'),        '/online_async_launch.py']),
    launch_arguments=[{'params': slam_config_path, 'use_sim_time': False}]
)

This gets it past the error for me, but it doesn't load the map transform until I run nav2_launch.py, then I have 2 rviz running and neither of them have a robot in them. But at that point, it loads in the map under map > map_save.pgm in the original SLAM rviz. 

After launching either again without closing one, it crashes my desktop machine and it takes a full reboot to get out of it.

"Ros2 topic echo /scan" shows values on desktop, so I think network is connecting correctly.

**Comment by bribribriambriguy** [comment]
Do you have the neato node running, you need it to publish the odom -> base_link transform, also when running the navigation launch file there is a default map file that you need to change with the launch argument map_path to the location of your map yaml file. I will change the slam_launch.py

**Comment by bribribriambriguy** [comment]
can you tell me if it works so i can close issue

**Comment by NMartin354** [comment]
It doesn't, your commit didn't upload correctly, I think I figured it out. 

The last time it crashed it literally broke the hard drive that I was running on, so I just got back up.  I don't have a map file, but you left a map in the location. It isn't coming up. rqt_robot_steering steers the node.

My map was on that drive.

How can I start building a map with this?


    slam = IncludeLaunchDescription(
      PythonLaunchDescriptionSource([os.path.join(
         get_package_share_directory('slam_toolbox'), 'launch'),
         '/online_async_launch.py']),
<<<<<<< HEAD:launch/slam_launch.py
      launch_arguments=[{'params': slam_config_path,
                         'use_sim_time': False}]
=======
      launch_arguments=[{'params': slam_config_path},{'use_sim_time': False}]
>>>>>>> 2e4406c16f2edd9e360f045f9bc9a809b1dfb179:neatonav2/launch/slam_launch.py
      )


   slam = IncludeLaunchDescription(
      PythonLaunchDescriptionSource([os.path.join(
         get_package_share_directory('slam_toolbox'), 'launch'),
         '/online_async_launch.py']),
      launch_arguments=[{'params': slam_config_path},{'use_sim_time': False}]
      )

Sorry it took so long.

**Comment by bribribriambriguy** [comment]
don't run the nav_launch.py along with the slam_launch.py

**Comment by NMartin354** [comment]
Got it! Thanks!

It's working now.
